schema: "classroom50/repo-config/v1"
classroom: "cprog"
assignment: "02-conveyor-belt"
owner:
  username: "Sheyar2004"
  id: 324073385
  accepted_at: "2026-09-13T17:33:24Z"
source:
  owner: "dtucprog"
  owner_id: 316954301
  repo: "02-conveyor-belt"
  branch: "main"
